### ISSUE TITLE
The accessibility/label-has-for rule does not accept input from frameworks.

### ISSUE THREAD

**Issue by rafinhacuri** [dethdkn/eslint-config#2]
Description:

The accessibility rule accessibility/label-has-for seems not to be accepting input from frameworks, resulting in accessibility compliance issues in our projects.

Expected Behavior:

We expect the accessibility rule to be compatible with the frameworks we use in our projects, allowing us to maintain high accessibility standards.

Current Behavior:

However, upon integrating this rule with our frameworks, we have noticed that it is not accepting their input, causing difficulties in ensuring the accessibility of our applications.

![imagem_2024-06-03_135234165](https://github.com/dethdkn/eslint-config/assets/75849138/5f32388d-8ff3-49bc-a0eb-0752701fff7f)

**Comment by dethdkn** [comment]
[🐛 Added required and components to accessibility/label-has-for](https://github.com/dethdkn/eslint-config/commit/cf3d3226c25686a2916c77c869400de10f838d7d)
